### ISSUE TITLE
Vocable trainer App Crashes ~ Bug 

### ISSUE THREAD

**Issue by beckysophie** [0xpr03/VocableTrainer-Android#25] opened 2018-03-30 07:32 UTC
***Expected Behavior***

It shouldn't crash, regardless of the position of the screen. Whether portrait or landscape. 

***Actual Behavior***

When a training session is successful, and screen goes landscape mode, the app crashes 

***How to produce the bug***

Open the app,  click on start new session ,click on the column A at the top to create a session, click on start session,Now when you get a message saying 'You've finished this training session',  rotate your screen(i.e landscape mode). The app would crash..... 

***TEST TOOLS***

* Operating system : Android 6.0
* Phone : Infinix hot s
* Vocable Trainer V0.5.3

***Recording of the bug is showned below......***

Watch the video below to see how it behaves.... 

https://youtu.be/Pl03Zeb8ihA

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@beckysophie/viable-trainer-app-crashes-bug">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by 0xpr03** [comment] 2018-04-02 00:26
Duplicate of #24

**Closed by 0xpr03** 2018-04-02 00:26 UTC
Labels: r:Utopian

**Comment by beckysophie** [comment] 2018-04-03 19:06
kindly review..... this isn't a duplicate.... 

the #24 stated that when the resume button is clicked

and mine(#25) clearly states that when a training session is successful and the screen is rotated, if the OK button is pressed, it would crash...... 

kindly read properly...... as there are lots of bug on your app 


Thank you

**Comment by 0xpr03** [comment] 2018-04-03 23:08
@beckysophie it is a duplicate as you started an invalid training session.
You shouldn't even be able to start a session over an empty selection, so of course it's a duplicate.

**Comment by beckysophie** [comment] 2018-04-11 14:07
Hey @0xpr03..... Am really sorry for what happened earlier...... 


I never meant those.... I guess I wasn't thinking from your perspective....... And plus I had a bad day the other day....... Hope to hear from you............

**Comment by PeerzadaZeeshan** [comment] 2018-04-11 14:13
I didn't know what had happened earlier?
Can you please explain me.

**Comment by PeerzadaZeeshan** [comment] 2019-10-02 03:13
Hey,

I just signed the petition "United Nations: Stand With Kashmir— It is been
almost 2 months of blockade." and wanted to see if you could help by adding
your name.

Our goal is to reach 100 signatures and we need more support. You can read
more and sign the petition here:

http://chng.it/JQnSF89Cph

Thanks!
Peerzada
